app/pic/forms.py
from flask import Flask, render_template
from flask_uploads import UploadSet, configure_uploads, IMAGES, patch_request_class
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import SubmitField
from extensions import photos


class PicUpLoadForm(FlaskForm):
    photo = FileField('图片文件', validators=[FileAllowed(photos, '只能上传图片！'), FileRequired('文件未选择！')])
    submit = SubmitField('上传')

app/pic/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

pic =Blueprint('pic', __name__)

from . import views,forms

app/pic/views.py
from .forms import PicUpLoadForm
from extensions import photos
from flask import flash, render_template, request, current_app, redirect,url_for
from . import pic
import hashlib
import time
import os


@pic.route('/', methods=['GET', 'POST'])
def upload_file():
    form = PicUpLoadForm()
    if form.validate_on_submit():
        for filename in request.files.getlist('photo'):
            md5 = hashlib.md5()
            md5.update(('admin'+str(time.time())).encode('utf-8'))
            name = md5.hexdigest()[:15]
            photos.save(filename, name=name+'.')
        flash('上传成功！')
    return render_template('pic/index.html', form=form)


@pic.route('/manage')
def manage_file():
    files_list = os.listdir(current_app.config['UPLOADED_PHOTOS_DEST'])
    return render_template('pic/manage.html', files_list=files_list)


@pic.route('/open/<filename>')
def open_file(filename):
    file_url = photos.url(filename)
    return render_template('pic/browser.html', file_url=file_url)


@pic.route('/delete/<filename>')
def delete_file(filename):
    file_path = photos.path(filename)
    os.remove(file_path)
    return redirect(url_for('pic.manage_file'))

app/templates/pic/browser.html
{% extends "base.html" %}


{% block title %}Flasky - 图片查看{% endblock %}

{% block page_content %}
<div class="row clearfix">
    <div class="col-md-12 column">
        <div class="page-header">
            <h1>查看图片</h1>
        </div>
        <ul class="nav nav-tabs">
            <li><a href="{{ url_for('pic.upload_file') }}">上传</a></li>
            <li><a href="{{ url_for('pic.manage_file') }}">管理</a></li>
        </ul>
        <div class="row clearfix">
            <div class="col-md-12 column">
                <p>图片完整链接: {{ file_url }}</p>
                <img src="{{ file_url }}">
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/pic/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}Flasky - 图片上传{% endblock %}

{% block page_content %}
<div class="row clearfix">
    <div class="col-md-12 column">
        <div class="page-header">
            <h1>上传图片</h1>
        </div>
        <ul class="nav nav-tabs">
            <li><a href="{{ url_for('pic.upload_file') }}">上传</a></li>
            <li><a href="{{ url_for('pic.manage_file') }}">管理</a></li>
        </ul>
        <div class="row clearfix">
            <div class="col-md-12 column">
                <form class="form form-horizontal" method="POST" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.photo, multiple="multiple") }}
                    {{ wtf.form_field(form.submit) }}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/pic/manage.html
{% extends "base.html" %}


{% block title %}Flasky - 图片管理{% endblock %}

{% block page_content %}
<div class="row clearfix">
    <div class="col-md-12 column">
        <div class="page-header">
            <h1>管理图片</h1>
        </div>
        <ul class="nav nav-tabs">
            <li><a href="{{ url_for('pic.upload_file') }}">上传</a></li>
            <li><a href="{{ url_for('pic.manage_file') }}">管理</a></li>
        </ul>
        <div class="row clearfix">
            <div class="col-md-12 column">
                {% for photo in files_list %}
                    - {{ photo }}
                    <a href="{{ url_for('pic.open_file', filename=photo) }}">打开</a>
                    <a href="{{ url_for('pic.delete_file', filename=photo) }}">删除</a><br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/pic/video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<video width="320" height="240" controls="controls">
  <source src="\static\video\dancing-with-gazelle.mp4" type="video/mp4" />
</video>
</body>
</html>